remove duplicate lines that cause compilation errors on mipsle
/usr/local/src/internal/runtime/atomic/atomic_mipsx.go:14:3: duplicate //go:linkname for Or64
/usr/local/src/internal/runtime/atomic/atomic_mipsx.go:15:3: duplicate //go:linkname for And64